### ISSUE TITLE
Partitions randomly have spikes of unacked messages

### ISSUE THREAD

**Issue by Xsixteen** [googleapis/java-pubsublite-kafka#244]
Hello -

We are using the Pubsub lite Kafka library and experience random spikes of queued data, that then burn down.   Is this expected behavior?  Is there any tuning settings which could prevent this from happening.

![image](https://user-images.githubusercontent.com/3039039/141232943-ed375d54-dd9b-4ab3-8db2-9132b3049b65.png)

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/java-pubsublite-kafka/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version:
3. Java version: 1.8.0_172-b11
4. pubsublite-kafka version(s): 0.6.3

#### Steps to reproduce

  1. Deploy code and consume from PubSub Lite topic.
  2. Run consumer for several hours, and observe spikes of unacked data.

#### Code example

```java
SubscriptionPath subscription = SubscriptionPath.newBuilder()
					.setLocation(CloudZone.of(CloudRegion.of(cloudRegion), zoneId))
					.setProject(ProjectNumber.of(Long.valueOf(projectId)))
					.setName(SubscriptionName.of(subscriptionId))
					.build();

			ConsumerSettings settings = ConsumerSettings.newBuilder()
					.setSubscriptionPath(subscription)
					.setPerPartitionFlowControlSettings(FlowControlSettings.builder()
							.setBytesOutstanding(bytesOutstanding)  // 10 MB
							.setMessagesOutstanding(Long.MAX_VALUE)
							.build())
					.setAutocommit(true).build();

			TopicPath topicPath =
					TopicPath.newBuilder()
							.setLocation(CloudZone.of(CloudRegion.of(cloudRegion), zoneId))
							.setProject(ProjectNumber.of(Long.valueOf(projectId)))
							.setName(TopicName.of(kafkaTopic))
							.build();

			isRunning = true;
			this.consumer = settings.instantiate();
			try  {
				// The consumer can only subscribe to the topic that it is associated to.
				// If this is the only subscriber for this subscription, it will take up
				// to 90s for the subscriber to warm up.
				consumer.subscribe(Arrays.asList(topicPath.toString()));
				while (true) {
					ConsumerRecords<byte[], byte[]> records = consumer.poll(Duration.ofMillis(100));
					for (ConsumerRecord<byte[], byte[]> record : records) {
					// persist data
						if(!isRunning) {
							getLogger().info("Stopping processor requested - Breaking Poll loop");
							break;
						}
					}
					if(!isRunning) {
						consumer.close();
						getLogger().info("Stopping processor requested - Breaking Event loop");
						break;
					}
				}
			} catch (Exception e) {
				getLogger().error("Exception encountered during message polling reason=", e);
				e.printStackTrace();
			}```

#### Stack trace
```
Any relevant stacktrace here.
```

#### External references such as API reference guides

- ?

#### Any additional information below


Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by dpcollins-google** [comment]
Marking as obsolete- this is likely a monitoring artifact. this metric is intended to measure whether your subscriber is falling minutes behind, not seconds. The metric is only reported every 60s and uses heavy caching internally to keep it low cost.
